package com.constructionlog.app.ui

import androidx.compose.runtime.Composable
import androidx.navigation.compose.rememberNavController
import com.constructionlog.app.data.LogWithImages
import com.constructionlog.app.data.PlanTaskEntity
import com.constructionlog.app.data.ProjectEntity

@Composable
@Suppress("UNUSED_PARAMETER")
fun AppScreen(
    mode: ScreenMode,
    logs: List<LogWithImages>,
    trash: List<LogWithImages>,
    editorState: EditorState,
    projects: List<ProjectEntity>,
    planTasks: List<PlanTaskEntity>,
    projectsLoaded: Boolean,
    selectedProjectId: Long?,
    onShowList: () -> Unit,
    onShowTrash: () -> Unit,
    onStartCreate: () -> Unit,
    onStartEdit: (LogWithImages) -> Unit,
    onSelectProject: (Long) -> Unit,
    onDelete: (Long) -> Unit,
    onRestore: (Long) -> Unit,
    onDeleteForever: (Long) -> Unit,
    onEditorProjectChange: (Long) -> Unit,
    onAddProject: (String) -> Unit,
    onRenameProject: (Long, String) -> Unit,
    onDeleteProject: (Long) -> Unit,
    onDateChange: (Long) -> Unit,
    onWeatherChange: (String) -> Unit,
    onLocationChange: (String) -> Unit,
    onContentChange: (String) -> Unit,
    onWorkersChange: (String) -> Unit,
    onWorkerNamesChange: (String) -> Unit,
    onSafetyChange: (String) -> Unit,
    onStageChange: (String) -> Unit,
    onRemarkChange: (String) -> Unit,
    onRemoveImage: (String) -> Unit,
    onSave: () -> Unit,
    authEnabled: Boolean,
    reauthSeconds: Int,
    autoBackupEnabled: Boolean,
    autoBackupSummary: String,
    onAuthEnabledChange: (Boolean) -> Unit,
    onReauthSecondsChange: (Int) -> Unit,
    onAutoBackupEnabledChange: (Boolean) -> Unit,
    onExportBackup: () -> Unit,
    onImportBackup: () -> Unit,
    onExportPdf: (Long) -> Unit,
    onClearAllData: () -> Unit,
    amapKeyConfigured: Boolean,
    onSaveAmapKey: (String) -> Unit,
    qWeatherKeyConfigured: Boolean,
    onSaveQWeatherKey: (String) -> Unit,
    qWeatherHostConfigured: Boolean,
    onSaveQWeatherHost: (String) -> Unit,
    onAddPlanTask: (title: String, detail: String, dueAt: Long?, priority: Int) -> Unit,
    onUpdatePlanTask: (id: Long, title: String, detail: String, dueAt: Long?, priority: Int) -> Unit,
    onTogglePlanTask: (id: Long, done: Boolean) -> Unit,
    onDeletePlanTask: (Long) -> Unit,
    onAddFromCamera: () -> Unit,
    onAddFromGallery: () -> Unit,
    onAutoFetchWeather: (Long) -> Unit
) {
    val navController = rememberNavController()
    AppNavigation(
        navController = navController,
        logs = logs,
        trash = trash,
        editorState = editorState,
        projects = projects,
        planTasks = planTasks,
        projectsLoaded = projectsLoaded,
        selectedProjectId = selectedProjectId,
        onShowList = onShowList,
        onShowTrash = onShowTrash,
        onStartCreate = onStartCreate,
        onStartEdit = onStartEdit,
        onSelectProject = onSelectProject,
        onDelete = onDelete,
        onRestore = onRestore,
        onDeleteForever = onDeleteForever,
        onEditorProjectChange = onEditorProjectChange,
        onAddProject = onAddProject,
        onRenameProject = onRenameProject,
        onDeleteProject = onDeleteProject,
        onDateChange = onDateChange,
        onWeatherChange = onWeatherChange,
        onLocationChange = onLocationChange,
        onContentChange = onContentChange,
        onWorkersChange = onWorkersChange,
        onWorkerNamesChange = onWorkerNamesChange,
        onSafetyChange = onSafetyChange,
        onStageChange = onStageChange,
        onRemarkChange = onRemarkChange,
        onRemoveImage = onRemoveImage,
        onSave = onSave,
        authEnabled = authEnabled,
        reauthSeconds = reauthSeconds,
        autoBackupEnabled = autoBackupEnabled,
        autoBackupSummary = autoBackupSummary,
        onAuthEnabledChange = onAuthEnabledChange,
        onReauthSecondsChange = onReauthSecondsChange,
        onAutoBackupEnabledChange = onAutoBackupEnabledChange,
        onExportBackup = onExportBackup,
        onImportBackup = onImportBackup,
        onExportPdf = onExportPdf,
        onClearAllData = onClearAllData,
        amapKeyConfigured = amapKeyConfigured,
        onSaveAmapKey = onSaveAmapKey,
        qWeatherKeyConfigured = qWeatherKeyConfigured,
        onSaveQWeatherKey = onSaveQWeatherKey,
        qWeatherHostConfigured = qWeatherHostConfigured,
        onSaveQWeatherHost = onSaveQWeatherHost,
        onAddPlanTask = onAddPlanTask,
        onUpdatePlanTask = onUpdatePlanTask,
        onTogglePlanTask = onTogglePlanTask,
        onDeletePlanTask = onDeletePlanTask,
        onAddFromCamera = onAddFromCamera,
        onAddFromGallery = onAddFromGallery,
        onAutoFetchWeather = onAutoFetchWeather
    )
}
