package com.constructionlog.app.ui

import androidx.compose.runtime.Composable
import androidx.navigation.compose.rememberNavController
import com.constructionlog.app.data.AcceptanceFormWithDetails
import com.constructionlog.app.data.LogWithImages
import com.constructionlog.app.data.PlanTaskEntity
import com.constructionlog.app.data.ProjectEntity

@Composable
@Suppress("UNUSED_PARAMETER")
fun AppScreen(
    mode: ScreenMode,
    logs: List<LogWithImages>,
    trash: List<LogWithImages>,
    editorState: EditorState,
    acceptanceForms: List<AcceptanceFormWithDetails>,
    acceptanceEditorState: AcceptanceEditorState,
    projects: List<ProjectEntity>,
    planTasks: List<PlanTaskEntity>,
    projectsLoaded: Boolean,
    selectedProjectId: Long?,
    onShowList: () -> Unit,
    onShowTrash: () -> Unit,
    onStartCreate: () -> Unit,
    onStartEdit: (LogWithImages) -> Unit,
    onStartCreateAcceptance: () -> Unit,
    onStartEditAcceptance: (AcceptanceFormWithDetails) -> Unit,
    onStartEditAcceptanceById: (Long, (Boolean) -> Unit) -> Unit,
    onSelectProject: (Long) -> Unit,
    onDelete: (Long) -> Unit,
    onRestore: (Long) -> Unit,
    onDeleteForever: (Long) -> Unit,
    onEditorProjectChange: (Long) -> Unit,
    onAcceptanceProjectChange: (Long) -> Unit,
    onAddProject: (String) -> Unit,
    onRenameProject: (Long, String) -> Unit,
    onDeleteProject: (Long) -> Unit,
    onDateChange: (Long) -> Unit,
    onWeatherChange: (String) -> Unit,
    onLocationChange: (String) -> Unit,
    onContentChange: (String) -> Unit,
    onWorkersChange: (String) -> Unit,
    onWorkerNamesChange: (String) -> Unit,
    onSafetyChange: (String) -> Unit,
    onStageChange: (String) -> Unit,
    onRemarkChange: (String) -> Unit,
    onRemoveImage: (String) -> Unit,
    onSave: () -> Unit,
    onAcceptanceTypeChange: (String) -> Unit,
    onAcceptanceStageChange: (String) -> Unit,
    onAcceptanceDateChange: (Long) -> Unit,
    onAcceptanceWeatherChange: (String) -> Unit,
    onAcceptanceLocationChange: (String) -> Unit,
    onAcceptanceInspectorChange: (String) -> Unit,
    onAcceptanceRemarkChange: (String) -> Unit,
    onAcceptanceUpdateItem: (Int, AcceptanceItemDraft) -> Unit,
    onAcceptanceAddItemImageFromCamera: (Int) -> Unit,
    onAcceptanceAddItemImageFromGallery: (Int) -> Unit,
    onAcceptanceAddItem: () -> Unit,
    onAcceptanceRemoveItem: (Int) -> Unit,
    onAcceptanceRemoveImage: (String) -> Unit,
    onAcceptanceSave: () -> Unit,
    onAcceptanceDelete: (Long) -> Unit,
    onAutoFetchAcceptanceWeather: (Long) -> Unit,
    authEnabled: Boolean,
    reauthSeconds: Int,
    autoBackupEnabled: Boolean,
    autoBackupSummary: String,
    onAuthEnabledChange: (Boolean) -> Unit,
    onReauthSecondsChange: (Int) -> Unit,
    onAutoBackupEnabledChange: (Boolean) -> Unit,
    onExportBackup: () -> Unit,
    onImportBackup: () -> Unit,
    onExportPdf: (Long) -> Unit,
    onClearAllData: () -> Unit,
    amapKeyConfigured: Boolean,
    onSaveAmapKey: (String) -> Unit,
    qWeatherKeyConfigured: Boolean,
    onSaveQWeatherKey: (String) -> Unit,
    qWeatherHostConfigured: Boolean,
    onSaveQWeatherHost: (String) -> Unit,
    onAddPlanTask: (title: String, detail: String, dueAt: Long?, priority: Int) -> Unit,
    onUpdatePlanTask: (id: Long, title: String, detail: String, dueAt: Long?, priority: Int) -> Unit,
    onTogglePlanTask: (id: Long, done: Boolean) -> Unit,
    onDeletePlanTask: (Long) -> Unit,
    onAddFromCamera: () -> Unit,
    onAddFromGallery: () -> Unit,
    onAutoFetchWeather: (Long) -> Unit,
    onAddAcceptanceFromCamera: () -> Unit,
    onAddAcceptanceFromGallery: () -> Unit,
    onboardingCompleted: Boolean,
    onCompleteOnboarding: () -> Unit
) {
    val navController = rememberNavController()
    AppNavigation(
        navController = navController,
        logs = logs,
        trash = trash,
        editorState = editorState,
        acceptanceForms = acceptanceForms,
        acceptanceEditorState = acceptanceEditorState,
        projects = projects,
        planTasks = planTasks,
        projectsLoaded = projectsLoaded,
        selectedProjectId = selectedProjectId,
        onShowList = onShowList,
        onShowTrash = onShowTrash,
        onStartCreate = onStartCreate,
        onStartEdit = onStartEdit,
        onStartCreateAcceptance = onStartCreateAcceptance,
        onStartEditAcceptance = onStartEditAcceptance,
        onStartEditAcceptanceById = onStartEditAcceptanceById,
        onSelectProject = onSelectProject,
        onDelete = onDelete,
        onRestore = onRestore,
        onDeleteForever = onDeleteForever,
        onEditorProjectChange = onEditorProjectChange,
        onAcceptanceProjectChange = onAcceptanceProjectChange,
        onAddProject = onAddProject,
        onRenameProject = onRenameProject,
        onDeleteProject = onDeleteProject,
        onDateChange = onDateChange,
        onWeatherChange = onWeatherChange,
        onLocationChange = onLocationChange,
        onContentChange = onContentChange,
        onWorkersChange = onWorkersChange,
        onWorkerNamesChange = onWorkerNamesChange,
        onSafetyChange = onSafetyChange,
        onStageChange = onStageChange,
        onRemarkChange = onRemarkChange,
        onRemoveImage = onRemoveImage,
        onSave = onSave,
        onAcceptanceTypeChange = onAcceptanceTypeChange,
        onAcceptanceStageChange = onAcceptanceStageChange,
        onAcceptanceDateChange = onAcceptanceDateChange,
        onAcceptanceWeatherChange = onAcceptanceWeatherChange,
        onAcceptanceLocationChange = onAcceptanceLocationChange,
        onAcceptanceInspectorChange = onAcceptanceInspectorChange,
        onAcceptanceRemarkChange = onAcceptanceRemarkChange,
        onAcceptanceUpdateItem = onAcceptanceUpdateItem,
        onAcceptanceAddItemImageFromCamera = onAcceptanceAddItemImageFromCamera,
        onAcceptanceAddItemImageFromGallery = onAcceptanceAddItemImageFromGallery,
        onAcceptanceAddItem = onAcceptanceAddItem,
        onAcceptanceRemoveItem = onAcceptanceRemoveItem,
        onAcceptanceRemoveImage = onAcceptanceRemoveImage,
        onAcceptanceSave = onAcceptanceSave,
        onAcceptanceDelete = onAcceptanceDelete,
        onAutoFetchAcceptanceWeather = onAutoFetchAcceptanceWeather,
        authEnabled = authEnabled,
        reauthSeconds = reauthSeconds,
        autoBackupEnabled = autoBackupEnabled,
        autoBackupSummary = autoBackupSummary,
        onAuthEnabledChange = onAuthEnabledChange,
        onReauthSecondsChange = onReauthSecondsChange,
        onAutoBackupEnabledChange = onAutoBackupEnabledChange,
        onExportBackup = onExportBackup,
        onImportBackup = onImportBackup,
        onExportPdf = onExportPdf,
        onClearAllData = onClearAllData,
        amapKeyConfigured = amapKeyConfigured,
        onSaveAmapKey = onSaveAmapKey,
        qWeatherKeyConfigured = qWeatherKeyConfigured,
        onSaveQWeatherKey = onSaveQWeatherKey,
        qWeatherHostConfigured = qWeatherHostConfigured,
        onSaveQWeatherHost = onSaveQWeatherHost,
        onAddPlanTask = onAddPlanTask,
        onUpdatePlanTask = onUpdatePlanTask,
        onTogglePlanTask = onTogglePlanTask,
        onDeletePlanTask = onDeletePlanTask,
        onAddFromCamera = onAddFromCamera,
        onAddFromGallery = onAddFromGallery,
        onAutoFetchWeather = onAutoFetchWeather,
        onAddAcceptanceFromCamera = onAddAcceptanceFromCamera,
        onAddAcceptanceFromGallery = onAddAcceptanceFromGallery,
        onboardingCompleted = onboardingCompleted,
        onCompleteOnboarding = onCompleteOnboarding
    )
}
